name: Deploy CloudOps Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cloudops-enterprise-platform
            git pull origin main
            docker build -t cloudops-app:latest .
            docker stop cloudops-app || true
            docker rm cloudops-app || true
            COMMIT_ID=$(git rev-parse --short HEAD)
            DEPLOY_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

            docker run -d \
            --name cloudops-app \
            -p 80:5000 \
            -e APP_VERSION="$COMMIT_ID" \
            -e GIT_COMMIT="$COMMIT_ID" \
            -e DEPLOYED_AT="$DEPLOY_TIME" \
            -e APP_ENV="production" \
            cloudops-app:latest